import React from 'react';
import { motion } from 'motion/react';
import { Shield, FileText, ChevronRight } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function Terms() {
  return (
    <div className="min-h-screen bg-[#0A0A0A] text-white pt-28 pb-20 px-6 relative overflow-hidden">
      {/* Background Elements */}
      <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-[#FFC107]/5 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute bottom-0 left-0 w-[400px] h-[400px] bg-purple-500/5 rounded-full blur-[100px] pointer-events-none" />

      <div className="max-w-4xl mx-auto relative z-10 space-y-12">
        
        {/* Header */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center space-y-6 mb-16"
        >
          <div className="w-20 h-20 mx-auto bg-gradient-to-br from-[#FFC107]/20 to-transparent p-[1px] rounded-2xl flex items-center justify-center">
            <div className="w-full h-full bg-[#121212] rounded-2xl flex items-center justify-center border border-white/5">
              <FileText className="w-8 h-8 text-[#FFC107]" />
            </div>
          </div>
          <div>
            <h1 className="text-4xl md:text-5xl font-black uppercase tracking-tight text-white mb-4">
              Terms & Conditions
            </h1>
            <p className="text-white/50 text-sm md:text-base max-w-xl mx-auto leading-relaxed">
              Welcome to RAPDO. By accessing or using our platform, you agree to be bound by these comprehensive terms crafted to ensure a secure, fair, and premium mobility ecosystem across Bihar and beyond.
            </p>
          </div>
        </motion.div>

        {/* Content Blocks */}
        <div className="space-y-8">
          
          <Section title="1. Platform Usage Rules">
            <p className="text-white/60 leading-relaxed text-sm">
              RAPDO provides a technology platform connecting riders with captain partners for mobility and parcel delivery logistics. You must be at least 18 years old to create an account. Usage of the platform requires a valid phone number and active internet connection for real-time tracking operations.
            </p>
          </Section>

          <Section title="2. Booking & Cancellation Policy">
            <ul className="space-y-3 text-white/60 text-sm leading-relaxed list-disc list-inside">
              <li>Bookings are confirmed only when a driver partner accepts the trip.</li>
              <li>Cancellations within 3 minutes of booking are free of charge.</li>
              <li>Late cancellations or no-shows may incur a base penalty fee dynamically calculated based on ETA and distance traveled by the captain.</li>
              <li>RAPDO reserves the right to cancel trips flagged by our AI security systems as potentially fraudulent or unsafe.</li>
            </ul>
          </Section>

          <Section title="3. Payment & Fare Estimates">
            <p className="text-white/60 leading-relaxed text-sm">
              Fares listed upfront are estimates generated by our proprietary routing algorithms. Final charges may vary based on route alterations, excessive traffic delays, or wait times exceeding 5 minutes. Payments must be settled immediately via Wallet, UPI, Cards, or Cash at the end of the trip.
            </p>
          </Section>

          <Section title="4. Parcel Liability Terms">
            <p className="text-white/60 leading-relaxed text-sm">
              Users utilizing RAPDO Parcel must ensure all goods are legally permitted. We strictly prohibit the transport of hazardous materials, illegal substances, live animals, or items exceeding ₹50,000 in intrinsic value. RAPDO acts purely as a logistic connector; maximum liability for any damaged or lost parcel is strictly capped at ₹1,000, subject to verification.
            </p>
          </Section>

          <Section title="5. Prohibited Activities">
            <p className="text-white/60 leading-relaxed text-sm">
              Users must not:
            </p>
            <ul className="space-y-3 text-white/60 text-sm leading-relaxed mt-3 ml-4 border-l border-[#FFC107]/20 pl-4">
              <li>Engage in abusive, threatening, or discriminatory behavior toward Driver Partners.</li>
              <li>Intentionally damage the interior or exterior of the assigned vehicle.</li>
              <li>Bypass the application mechanics to negotiate private fares (Off-app trips void all RAPDO safety guarantees and insurance).</li>
              <li>Create multiple accounts to abuse promotional credits.</li>
            </ul>
          </Section>

          <Section title="6. Account Suspension">
            <p className="text-white/60 leading-relaxed text-sm">
              RAPDO's Trust & Safety AI monitors ecosystem health. We reserve the right to immediately suspend or permanently terminate access to the platform for accounts found violating these terms, exhibiting high cancellation rates, or presenting a risk to the community.
            </p>
          </Section>

          <Section title="7. Dispute Resolution">
            <p className="text-white/60 leading-relaxed text-sm">
              All disputes arising under these terms shall be subject to the exclusive jurisdiction of the courts located in Patna, Bihar. We mandate a 30-day internal mediation window through our Support Center before any formal legal proceedings may commence.
            </p>
          </Section>

        </div>

        {/* Footer Actions */}
        <motion.div 
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          className="pt-12 border-t border-white/10 flex flex-col sm:flex-row items-center justify-between gap-6"
        >
          <div className="text-xs text-white/40 uppercase tracking-widest font-bold">
            Last Updated: May 2026 • Ver 4.2
          </div>
          <div className="flex gap-4">
            <Link to="/privacy" className="px-6 py-3 rounded-full bg-white/5 hover:bg-white/10 text-white text-xs font-bold uppercase tracking-widest transition-all">
              Privacy Policy
            </Link>
            <Link to="/contact" className="px-6 py-3 rounded-full bg-[#FFC107] hover:bg-[#FFB300] text-black text-xs font-bold uppercase tracking-widest transition-all">
              Contact Legal
            </Link>
          </div>
        </motion.div>

      </div>
    </div>
  );
}

function Section({ title, children }: { title: string, children: React.ReactNode }) {
  return (
    <motion.div 
      initial={{ opacity: 0, y: 10 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      className="bg-[#121212] border border-white/5 p-8 rounded-3xl group hover:border-white/10 transition-all"
    >
      <h3 className="text-lg font-black text-white uppercase tracking-wider mb-4 flex items-center gap-3">
        <div className="w-1.5 h-1.5 bg-[#FFC107] rounded-full" />
        {title}
      </h3>
      {children}
    </motion.div>
  );
}
